remote_theme: pages-themes/midnight@v0.2.0
title: Deed
description: Deeds are 10,000 randomly generated lists of items that represent ownership of a figurative piece of property, on-chain, for your Adventurer. 
